fix: provenance to both github and npmjs registry
fix: provenance to both github and npmjs registry

diff --git a/.github/workflows/publish-package-after-release.yml b/.github/workflows/publish-package-after-release.yml
--- a/.github/workflows/publish-package-after-release.yml
+++ b/.github/workflows/publish-package-after-release.yml
@@ -11,17 +11,14 @@ concurrency:
 
 permissions:
   contents: read
-  packages: write
-  id-token: write # to enable use of OIDC for npm provenance
 
 env:
   NPM_CONFIG_FUND: "false"
 
 jobs:
-  publish-package:
-    name: Publish package
+  build:
+    name: Build package
     runs-on: ubuntu-latest
-    environment: release
     steps:
       - name: Checkout
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
@@ -35,7 +32,6 @@ jobs:
         uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
         with:
           node-version-file: package.json
-          registry-url: https://registry.npmjs.org
           cache: pnpm
           cache-dependency-path: pnpm-lock.yaml
 
@@ -58,15 +54,96 @@ jobs:
         run: |
           pnpm run build
 
-      - name: Publish to GitHub Packages
+      - name: Upload package artifact
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+        with:
+          name: package
+          if-no-files-found: error
+          path: |
+            dist
+            package.json
+            README.md
+            LICENSE
+
+  publish-github-packages:
+    name: Publish to GitHub Packages
+    runs-on: ubuntu-latest
+    environment: release
+    needs:
+      - build
+    permissions:
+      contents: read
+      packages: write
+      id-token: write # to enable use of OIDC for npm provenance
+    steps:
+      - &download_artifact
+        name: Download package artifact
+        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+        with:
+          name: package
+
+      - name: Set up node
+        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
+        with:
+          node-version-file: package.json
+          registry-url: https://npm.pkg.github.com
+
+      - name: Publish
         shell: bash
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
-          pnpm publish --no-git-checks --registry https://npm.pkg.github.com
+          npm publish --provenance --access public
 
-      - name: Publish to npm (trusted publishing via OIDC)
+  publish-npmjs:
+    name: Publish to npmjs
+    runs-on: ubuntu-latest
+    environment: release
+    needs:
+      - build
+    permissions:
+      contents: read
+      id-token: write # to enable use of OIDC for npm provenance
+    steps:
+      - *download_artifact
+
+      - name: Set up node
+        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
+        with:
+          node-version-file: package.json
+          registry-url: https://registry.npmjs.org
+
+      - name: Publish (trusted publishing via OIDC)
         shell: bash
         run: |
           npm publish --provenance --access public
+
+  all-done:
+    name: All done
+    # this is the job that should be marked as required on GitHub. It's the only one that'll reliably trigger
+    # when any upstream fails: success
+    # when all upstream skips: pass
+    # when all upstream success: success
+    # combination of upstream skip and success: success
+    runs-on: ubuntu-latest
+    needs:
+      - build
+      - publish-github-packages
+      - publish-npmjs
+    if: |
+      always()
+    steps:
+      - name: Fail!
+        shell: bash
+        if: |
+          contains(needs.*.result, 'failure') ||
+          contains(needs.*.result, 'cancelled')
+        run: |
+          echo "One / more upstream failed or was cancelled. Failing job..."
+
+          exit 1
+
+      - name: Success!
+        shell: bash
+        run: |
+          echo "Great success!"
